.rubocop.yml:
  default_configs:
    Layout/IndentHeredoc:
      Enabled: false
    Style/DoubleNegation:
      Enabled: false
    Style/GuardClause:
      Enabled: false
    Style/MultilineBlockChain:
      Enabled: false
    RSpec/FilePath:
      Enabled: false
    RSpec/InstanceVariable:
      Exclude: ['spec/integration/provider/mount_spec.rb']
    RSpec/AnyInstance:
      Exclude: ['spec/integration/provider/mount_spec.rb']
    RSpec/ExpectInHook:
      Exclude: ['spec/integration/provider/mount_spec.rb']
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw
      - gem: beaker
        version: '~> 3.34'
        from_env: BEAKER_VERSION
      - gem: beaker-abs
        from_env: BEAKER_ABS_VERSION
        version: '~> 0.5'
      - gem: beaker-pe
      - gem: beaker-hostgenerator
        from_env: BEAKER_HOSTGENERATOR_VERSION
      - gem: beaker-rspec
        from_env: BEAKER_RSPEC_VERSION
      - gem: beaker-puppet
        from_env: BEAKER_PUPPET_VERSION
        version: '~> 0.14'
    ':development':
      - gem: puppet-strings
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
.travis.yml:
  remove_includes:
    - env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9
